[SALEOR-3686] Extend checkout type to return list of active payments
SaleorIntegrations/saleor pull request #8
Opened 2021-08-16 11:35 UTC by pzborow

I want to merge this change because...

We need to have a IDs of payments assigned to checkout. We will need them to pass them as an argument for new mutation checkoutPaymentComplete.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2021-08-17 12:39 UTC, stnatic requested changes

2021-08-17 12:39 UTC, stnatic commented on saleor/graphql/checkout/tests/test_checkout.py
> +    query = """
I've noticed that other Saleor test are defining graphql strings globally. I would keep it consistent

2021-08-17 12:39 UTC, stnatic commented on saleor/graphql/checkout/tests/test_checkout.py
> +    payment_dummy.is_active = False
I would use parameterise for that - otherwise this test breaks the "given, when, then" rule

2021-08-17 12:39 UTC, stnatic commented on saleor/graphql/checkout/types.py
> +        return root.payments.filter(is_active=True)
Please make sure that the data loaders are correctly used. Check other unit tests whether Django's assertNumQueries is used

2021-08-18 07:37 UTC, korycins commented on saleor/graphql/checkout/tests/test_checkout.py
> +    payment_dummy.save()
IMo this should be a separate test. or single test with pytest.mark.parametrize

2021-08-18 07:37 UTC, korycins commented on saleor/graphql/payment/types.py
> +class CheckoutActivePayment(CountableDjangoObjectType):
As we talked. Instead of creating new type, we should use the existing one.

2021-08-19 08:52 UTC, pzborow commented on saleor/graphql/checkout/tests/test_checkout.py
> +    query = """
OK

2021-08-19 08:53 UTC, pzborow commented on saleor/graphql/checkout/tests/test_checkout.py
> +    payment_dummy.is_active = False
OK

2021-08-19 13:46 UTC, pzborow commented on saleor/graphql/checkout/types.py
> +        return root.payments.filter(is_active=True)
OK

2021-08-19 13:46 UTC, pzborow commented on saleor/graphql/checkout/tests/test_checkout.py
> +    payment_dummy.save()
OK

2021-08-20 08:19 UTC, pzborow commented on saleor/graphql/payment/types.py
> +class CheckoutActivePayment(CountableDjangoObjectType):
Joined both types to Payment. After consultation with Maciek, limiting list of fields will be done in different task

2021-08-20 13:30 UTC, stnatic commented on saleor/tests/fixtures.py
> -    yield context
this doesn't look expected?

2021-09-06 13:54 UTC, closed without merging